version: "3.8"
services: 
    python:
        build: data
        env_file: .env
        volumes: 
            - "./data:/app"
        depends_on:
            - "db"
    db:
        image: postgres:13.1
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - db-volume:/var/lib/postgresql/data

volumes:
   db-volume: