version: "3.8"
services: 
    python:
        build: data
        env_file: .env
        volumes: 
            - "./data:/app" #for code sync
        depends_on:
            - "db"
    db:
        image: postgres:13.1
        restart: always
        env_file: .env
        ports:
            - 5432:5432
        volumes:
            - db-volume:/var/lib/postgresql/data
    
    rdf:
        image: ontotext/graphdb:9.5.0-se
        ports:
            - 7200:7200
        volumes:
            - rdf-volume:/opt/graphdb/home
            - ./license:/opt/graphdb/home/conf # for graphdb se license


volumes:
   db-volume:
   rdf-volume: