ARG USER
ARG USER_ID
ARG GROUP_ID

# pull the base image
FROM node:15.10.0-buster-slim

# set the working direction
WORKDIR /app

USER ${USER}

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json .
COPY package-lock.json .
# RUN npm install  # run only oh the first time!!

# start app
CMD ["npm", "start"]
