FROM python:3.7-slim-buster
WORKDIR /app

COPY requirements.txt .

# Some package requires gcc to be builded.
RUN apt-get update && apt-get install -y libpq-dev gcc \
    && pip install -r requirements.txt \
    && apt-get autoremove -y gcc

CMD [ "python", "run.py"]


